services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=TestApp2025!
      - MYSQL_DATABASE=TestAppDB
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=TestApp2025!
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -pTestApp2025! --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - testAppNet

    volumes:
      - mysqldata:/var/lib/mysql

  productsapi:
    build:
      context: ./src/ProductService
      dockerfile: Api/Dockerfile
    container_name: ProductService
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=TestAppDB;Uid=sa;Pwd=TestApp2025!;
    ports:
      - "5000:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - testAppNet

  inventoryapi:
    build:
      context: ./src/InventoryService
      dockerfile: Api/Dockerfile
    container_name: InventoryService
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=TestAppDB;Uid=sa;Pwd=TestApp2025!;
    ports:
      - "5001:8080"
    depends_on:
      db:
        condition: service_healthy
      depends_on:
        - rabbitmq
      networks:
        - testAppNet
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # para acceder al dashboard en http://localhost:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    depends_on:
      db:
        condition: service_healthy
    networks:
      - testAppNet

networks:
  testAppNet:
    driver: bridge
volumes:
  mysqldata:
