services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-CU12-ubuntu-20.04
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TestApp2025!
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P TestApp2025! -Q 'SELECT 1' || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 10
    networks:
      - productsnet
    #volumes:
    #  - sqlserverdata:/var/opt/mssql

  productsapi:
    build:
      context: ./src/ProductService
      dockerfile: Api/Dockerfile
    container_name: ProductService
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=ProductsDb;User=sa;Password=TestApp2025!;TrustServerCertificate=True;
    ports:
      - "5000:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - productsnet

networks:
  productsnet:
    driver: bridge
volumes:
  sqlserverdata:
